# Estrutura de dados DataFrame

O DataFrame é uma estrutura de dados que é o coração da biblioteca Pandas, muito usado em tarefas de filtragem. <br>
O DataFrame é conceitualmente um objeto bidimensional, em que há um índice e varias colunas de conteúdo com cada coluna possuindo um rótulo.

In [1]:
# Importando a biblioteca 
import pandas as pd

In [5]:
# Vamos criar três registros escolares paraestudantes e suas notas. Criarei uma série para cada nome de estudante, o nome da matéria e a pontuação.

registro1 = pd.Series({'Nome': 'Alice',
                       'Curso': 'Física',
                       'Nota': 8.5})

registro2 = pd.Series({'Nome': 'Jack',
                       'Curso': 'Química',
                       'Nota': 8.2})

registro3 = pd.Series({'Nome': 'Helen',
                       'Curso': 'Biologia',
                       'Nota': 9})

In [16]:
# Como uma série, o DataFrame é indexado. Usaremos um grupo de séries em que cada série representa uma linha de dados.
# Assim como as funções de séries, podemos passar os nossos itens idividuais em um array e podemos passar os nomes dos índices. 

# Criando um DataFrame
df = pd.DataFrame([registro1, registro2, registro3], index = ['aluno1', 'aluno2', 'aluno3'])

# Vamos olhar as 5 primeiras linhas
df.head()

         Nome     Curso  Nota
aluno1  Alice    Física   8.5
aluno2   Jack   Química   8.2
aluno3  Helen  Biologia   9.0

In [ ]:
# Um método alternativo seria usar uma lista de dicionários, em que cada dicionário representa uma l  inha de dados. 

estudantes = [{'Nome': 'Alice',
               'Curso': 'Física',
               'Nota': 8.5}, 
                {'Nome': 'Jack',
                'Curso': 'Química',
                'Nota': 8.2},
                {'Nome': 'Helen',
                'Curso': 'Biologia',
                'Nota': 9}]

# Agora passamos essa lista de dicionários para o DataFrame
df = pd.DataFrame(estudantes, index = ['aluno1', 'aluno2', 'aluno3'])
df

         Nome     Curso  Nota
aluno1  Alice    Física   8.5
aluno2   Jack   Química   8.2
aluno3  Helen  Biologia   9.0

In [26]:
# Podemos extrair dados usando os atributos 'iloc' e 'loc'. 
# Dado que o DataFrame é bidimensional, passando um único valor para o operador de indexação loc, iremos retornar uma série se houver apenas uma linha de retorno.

# Por exemplo, se quisermos selecionar dados associados ao aluno2 apenas consultamo o atributo '.loc' com um único parâmetro.
df.loc['aluno2']

Nome        Jack
Curso    Química
Nota         8.2
Name: aluno2, dtype: object

Perceba que o nome da série é apresendado como valor do índice (o nome da linha), enquanto que o nome da coluna é incluído na saída

In [29]:
# Podemos verificar o tipo de dado da resposta usando a função 'type()' do Python.

type(df.loc['aluno2'])

pandas.Series

In [ ]:
# É importante lembrar que os índices e os nomes das colunas ao longo dos eixos horizontal e vertical podem não ser únicos (unique). 

alunos_escola = [{'Nome': 'Alice',
               'Curso': 'Física',
               'Nota': 8.5}, 
                {'Nome': 'Jack',
                'Curso': 'Química',
                'Nota': 8.2},
                {'Nome': 'Helen',
                'Curso': 'Biologia',
                'Nota': 9}]

df = pd.DataFrame(estudantes, index = ['escola1', 'escola2', 'escola1'])

# Nesse exemplo, vamos ver dois registros para o 'escola1' como linhas diferentes.
# Neste caso, como o nome da linha não é único, vamos ter, não uma série nova, mas sim um DataFrame novo
df.loc['escola1']

          Nome     Curso  Nota
escola1  Alice    Física   8.5
escola1  Helen  Biologia   9.0

In [31]:
# Aqui podemos ver o tipo de dados diferente.

type(df.loc['escola1'])

pandas.DataFrame