# Estrutura de dados DataFrame

O DataFrame é uma estrutura de dados que é o coração da biblioteca Pandas, muito usado em tarefas de filtragem. <br>
O DataFrame é conceitualmente um objeto bidimensional, em que há um índice e varias colunas de conteúdo com cada coluna possuindo um rótulo. 

Um DataFrame é como uma tabela: 
- Linhas → representam registros (ex: alunos)
- Colunas → representam atributos (ex: nome, idade)
- Célula (é a menor unidade de um dado dentro de um DataFrame) → valor individual (ex: idade da Ana = 20)

In [130]:
# Importando a biblioteca 
import pandas as pd

In [131]:
# Vamos criar três registros escolares paraestudantes e suas notas. Criarei uma série para cada nome de estudante, o nome da matéria e a pontuação.

registro1 = pd.Series({'Nome': 'Alice',
                       'Curso': 'Física',
                       'Nota': 8.5})

registro2 = pd.Series({'Nome': 'Jack',
                       'Curso': 'Química',
                       'Nota': 8.2})

registro3 = pd.Series({'Nome': 'Helen',
                       'Curso': 'Biologia',
                       'Nota': 9})

In [132]:
# Como uma série, o DataFrame é indexado. Usaremos um grupo de séries em que cada série representa uma linha de dados.
# Assim como as funções de séries, podemos passar os nossos itens idividuais em um array e podemos passar os nomes dos índices. 

# Criando um DataFrame
df = pd.DataFrame([registro1, registro2, registro3], index = ['aluno1', 'aluno2', 'aluno3'])

# Vamos olhar as 5 primeiras linhas
df.head()

         Nome     Curso  Nota
aluno1  Alice    Física   8.5
aluno2   Jack   Química   8.2
aluno3  Helen  Biologia   9.0

In [133]:
# Um método alternativo seria usar uma lista de dicionários, em que cada dicionário representa uma l  inha de dados. 

estudantes = [{'Nome': 'Alice',
               'Curso': 'Física',
               'Nota': 8.5}, 
                {'Nome': 'Jack',
                'Curso': 'Química',
                'Nota': 8.2},
                {'Nome': 'Helen',
                'Curso': 'Biologia',
                'Nota': 9}]

# Agora passamos essa lista de dicionários para o DataFrame
df = pd.DataFrame(estudantes, index = ['aluno1', 'aluno2', 'aluno3'])
df

         Nome     Curso  Nota
aluno1  Alice    Física   8.5
aluno2   Jack   Química   8.2
aluno3  Helen  Biologia   9.0

In [134]:
# Podemos extrair dados usando os atributos 'iloc' e 'loc'. 
# Dado que o DataFrame é bidimensional, passando um único valor para o operador de indexação loc, iremos retornar uma série se houver apenas uma linha de retorno.

# Por exemplo, se quisermos selecionar dados associados ao aluno2 apenas consultamo o atributo '.loc' com um único parâmetro.
df.loc['aluno2']

Nome        Jack
Curso    Química
Nota         8.2
Name: aluno2, dtype: object

Perceba que o nome da série é apresendado como valor do índice (o nome da linha), enquanto que o nome da coluna é incluído na saída

In [135]:
# Podemos verificar o tipo de dado da resposta usando a função 'type()' do Python.

type(df.loc['aluno2'])

pandas.Series

In [136]:
# É importante lembrar que os índices e os nomes das colunas ao longo dos eixos horizontal e vertical podem não ser únicos (unique). 

alunos_escola = [{'Nome': 'Alice',
               'Curso': 'Física',
               'Nota': 8.5}, 
                {'Nome': 'Jack',
                'Curso': 'Química',
                'Nota': 8.2},
                {'Nome': 'Helen',
                'Curso': 'Biologia',
                'Nota': 9}]

df = pd.DataFrame(estudantes, index = ['escola1', 'escola2', 'escola1'])

# Nesse exemplo, vamos ver dois registros para o 'escola1' como linhas diferentes.
# Neste caso, como o nome da linha não é único, vamos ter, não uma série nova, mas sim um DataFrame novo
df.loc['escola1']

          Nome     Curso  Nota
escola1  Alice    Física   8.5
escola1  Helen  Biologia   9.0

In [137]:
# Aqui podemos ver o tipo de dados diferente.

type(df.loc['escola1'])

pandas.DataFrame

In [138]:
# Um dos poderes do DataFrame do Pandas é que conseguimos selecionar rapidamente dados baseados em vários eixos. 
# Por exemplo, se quisermos apenas listar os nomes dos alunos da 'escola1', podemos fornecer dois parâmetros para '.loc', sendo um o índice de linha (o nome da linha) e o outro sendo o nome da coluna.

# Vamos supor que estamos interessados em alguns estudantes da 'escola1'
df.loc['escola1', 'Nome']

escola1    Alice
escola1    Helen
Name: Nome, dtype: str

Perceba que isso é uma série do Pandas

In [139]:
df.loc['escola1', ['Nome', 'Nota']]

          Nome  Nota
escola1  Alice   8.5
escola1  Helen   9.0

Aqui já é um DataFrame. Isso, pois temos duas colunas de atributos

In [140]:
# O que faríamos se quiséssemos que ele selecionasse linhas de coluna única? 
# Existem alguns mecanismos. Primeiro, fazemos a transposição da matriz, o que transforma todas as linhas em colunas e todas as colunas em linhas, e isso é feito com o atributo 'T'.

df.T

      escola1  escola2   escola1
Nome    Alice     Jack     Helen
Curso  Física  Química  Biologia
Nota      8.5      8.2       9.0

In [141]:
# Para usarmos '.loc' na matriz transposta para obter apenas os nomes dos estudantes faremos:

df.T.loc['Nome']

escola1    Alice
escola2     Jack
escola1    Helen
Name: Nome, dtype: object

##### ATENÇÃO: Tanto .loc quanto .iloc são usados para selecionar linhas.

OBS: Use a transposta apenas se necessariamente precisar, pois tem métodos melhores para selecionar apenas colunas específicas com menor custo.

In [142]:
# Pandas disponibiliza o operador de indexação diretamente no DataFrame para selecionar a coluna. Em DataFrames as colunas SEMPRE possuem um nome (um título), e, assim, a seleção será sempre baseada no seu nome.

df['Nome']

escola1    Alice
escola2     Jack
escola1    Helen
Name: Nome, dtype: str

In [143]:
# Para acessar duas colunas:
df[['Nome', 'Curso']]

          Nome     Curso
escola1  Alice    Física
escola2   Jack   Química
escola1  Helen  Biologia

In [144]:
# Na prática, isso funciona muito bem, uma vez que estamos frequentemente tentando adicionar ou remover colunas. No entanto, isso signfica que podemos receber um erro de chave quando tentamos usar o .loc com um nome de coluna.

'''df.loc['Nome']'''          # ERRO

"df.loc['Nome']"

In [145]:
# Note também que o resultado de uma única projeção de coluna é um objeto do tipo Série 

type(df['Nome'])

pandas.Series

In [146]:
# Uma vez que o resultado do operador de indexação é um DataFrame ou uma Série, podemos usar essas operações juntas. Por exemplo, podemos selecionar todas as linhas que são relacionadas com 'escola1' usando .loc, e obtemos pelo nome da coluna apenas para essas linhas. 

df.loc['escola1']['Nome']

escola1    Alice
escola1    Helen
Name: Nome, dtype: str

In [147]:
# Para mais de uma coluna: 
df.loc['escola1'][['Nome', 'Curso']]

          Nome     Curso
escola1  Alice    Física
escola1  Helen  Biologia

Mas qual é a diferença entre: 

- df.loc['escola1', 'Nome']
- df.loc['escola1', ['Nome']]
- df.loc['escola1']['Nome']

A PRINCIPAL diferença está na eficiência. <br>
No primeiro caso (df.loc['escola1', 'Nome']), é acessado a linha escola1 e a coluna nome DIRETO. <br>
No segundo caso (df.loc['escola1', ['Nome']]), acontece a mesma coisa, porém como é passado em forma de lista as colunas, então ao invés de formatar com Série é formatado com DataFrame. <br>
Ja no terceiro caso (df.loc['escola1']['Nome']), primeiro é acessado a linha, de forma inteira, depois dessa linha(s), filtra-se a coluna 'Nome'. Nesse caso, temos duas operações, então é menos eficiente. 

Sendo assim, a terceira opção, isto é, encadeando por indexação no retorno da função de outro índice, possui custo, pois ele quebra a operação em duas etapas separadas, então é melhor evitar se você puder fazer de outra forma. Particularmente, o encadeamento tente a fazer com que o Pandas retorne uma cópia do DataFrame (ou uma cópia de parte do DataFrame) ao invés de trazer uma 'view' do DataFrame. Dessa forma, para selecionar dados, essa não é uma boa opção.

In [148]:
# Uma outra abordagem é: à medida em que vemos que .loc faz a seleção da linha, e pode ter dois parâmetros, o índice da linha e uma lista dos nomes das colunas, o .loc também suporta fatiar (operação de fatiamento).

# Se quisermos selecionar todas as linhas, podemos usar dois pontos para indicar todos os registros do começo ao fim. Isso é como fatiar caracteres em uma lista em Python.
# Em seguida, podemos adicionar o nome da coluna como o segundo parâmetro em uma str, e se quiséssemos incluir várias colunas, podemos fazer na forma de lista e teremos como retorno somente as colunas que pedimos.

# Por exemplo, no qual pedimos todos os nomes e as notas de todas as escolas usando o operador .loc
df.loc[:, ['Nome', 'Nota']]

          Nome  Nota
escola1  Alice   8.5
escola2   Jack   8.2
escola1  Helen   9.0

Entre:
- df.loc[:, ['Nome', 'Nota']]
- df[['Nome', 'Nota']]

Não há diferença, apenas na escrita mesmo

In [149]:
# Vamos ver como deletar dados de Séries e de DataFrames, e podemos usar a função 'drop()' para isso.
# Essa função leva um único parâmetro, que é o índice/rótulo de linha a remover. 
# ATENÇÃO: A função drop() não altera o DataFrame original, em vez disso, a função drop() retorna uma cópia do DataFrame com as linhas informadas removidas 

df.drop('escola1')

         Nome    Curso  Nota
escola2  Jack  Química   8.2

In [150]:
# Agora vamos olhar o original:
df

          Nome     Curso  Nota
escola1  Alice    Física   8.5
escola2   Jack   Química   8.2
escola1  Helen  Biologia   9.0

Perceba que ainda está igual o original

In [151]:
# A função drop() tem dois parâmetros opcionais. 
# - O primeiro é chamado "inplace", e se estiver definido como verdadeiro, ai sim o DataFrame original será modificado ao invés de retornar uma cópia
# - O segundo é chamado "axis", definindo qual eixo será descartado, e, por padrão, o seu valor é ZERO (0), indicando o eixo da LINHA. Porém, podemos mudar para UM (1) se quisermos descartar a coluna. 

copia_df = df.copy()

# Agora vamos remover uma coluna
copia_df.drop('Nota', axis = 1, inplace = True)
copia_df

          Nome     Curso
escola1  Alice    Física
escola2   Jack   Química
escola1  Helen  Biologia

Perceba que a coluna NOTA foi removida, e de forma definitiva

**OBS:** Existem várias funções que possuem retornam cópia, a menos que diga a elas para alterar o original (inplace = True). Essas funções, chamamos de métodos inplace ou métodos mutáveis, porém hoje em dia, a recomendação da comunidade pandas é evitar inplace=True e preferir: df = df.dropna(), pois é mais previsível, evita bugs e facilita encadeamento de métodos.

In [152]:
# Há, no entanto, uma outra forma de descartar colunas, e isso é diretamente através do uso de um operador de indexação usando a palavra chave 'del'. Dessa forma, estaremos removendo dados, no entanto, produz efeitos imediatos sobre o DataFrame e não apresenta mais os dados removidos.
del copia_df['Curso']
copia_df

          Nome
escola1  Alice
escola2   Jack
escola1  Helen

In [153]:
# Agora vamos remover uma linha
copia_df.drop('escola1', inplace = True)
copia_df

         Nome
escola2  Jack

#### CUIDADO: Perceba que foi deletadas TODAS as linhas que tinham o mesmo nome 'escola1'

In [155]:
import numpy as np

In [157]:
# Podemos adicionar uma nova coluna ao DataFrame, basta usar um valor usando o operador de indexação, como no dicionário. 
# Por exemplo, se quisermos adicionar uma coluna 'ClassRanking' com o valor default igual 'NaN', podemos fazê-lo usando o operador de atribuição. 

copia_df['ClassRanking'] = np.nan
copia_df

         Nome  ClassRanking
escola2  Jack           NaN

Todas as linhas ficam com o valor padrão