# Valores ausentes

Vimos uma prévia de como o Pandas lida com valores ausentes usando o tipo NaN. <br>
Valores ausentes são muito comuns em atividades de limpeza de dados, e valores ausentes podem existir por vários motivos:

- Pode haver, dentro de uma pesquisa, respostas que o respondente não forneceu, ou seja, uma OMISSÃO. Esse dado ausente, chamamos de **Missing at Random** (ausente aleatoriamente) se houvver outras variáveis que possam ser usadas para prever a variável que está ausente. Se os dados faltantes não possuem relação com nenhuma outra variável chamamos esses dados de **Missing Completely at Random** (desaparecidos completamente de forma aleatória)
- Dados ausentes por não terem sido coletados

In [41]:
# Importando a biblioteca 
import pandas as pd

In [42]:
# Pandas é muito bom em detectar valores ausentes diretaemnte de arquivos como CSV.
# Embora a maioria dos valores ausentes geralmente seja formatada como NaN, null, None, NA, às vezes os valores ausentes não são rotulados de forma tão clara, por exemplo, utilizar 99 em categorias binárias para indicar que é um valor ausente.

# A função pandas read_csv() tem um parâmetro chamado "na_values" que nos permite especificar o formato dos valores ausentes. Ele permite que sequências escalares, listas ou dicionários sejam usados.
df = pd.read_csv('datasets/class_grades.csv')
df.head(10)

   Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0       5       57.14     34.09    64.38     51.48  52.50
1       8       95.05    105.49    67.50     99.07  68.33
2       8       83.70     83.17      NaN     63.15  48.89
3       7         NaN       NaN    49.38    105.93  80.56
4       8       91.32     93.64    95.00    107.41  73.89
5       7       95.00     92.58    93.12     97.78  68.06
6       8       95.05    102.99    56.25     99.07  50.00
7       7       72.85     86.85    60.00       NaN  56.11
8       8       84.26     93.10    47.50     18.52  50.83
9       7       90.10     97.55    51.25     88.89  63.61

Perceba que existem vários valores ausentes apenas nessas 10 linhas.

In [43]:
# Podemos usar a função .isnull() para criar uma máscara booleana de todo o quadro de dados. Isso vai funcionar por broadcast
mascara = df.isnull()
mascara

    Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0    False       False     False    False     False  False
1    False       False     False    False     False  False
2    False       False     False     True     False  False
3    False        True      True    False     False  False
4    False       False     False    False     False  False
..     ...         ...       ...      ...       ...    ...
94   False        True     False    False     False  False
95   False        True     False    False     False  False
96   False       False     False    False     False  False
97   False       False     False    False     False  False
98   False       False     False    False     False  False

[99 rows x 6 columns]

In [44]:
# Isso pode ser útil para processar linhas com base em determinadas colunas de dados. Outra operação útil é poder eliminar todas as linhas que têm dados ausentes, o que pode ser feito com a função dropna()
df.dropna().head(10)

    Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0        5       57.14     34.09    64.38     51.48  52.50
1        8       95.05    105.49    67.50     99.07  68.33
4        8       91.32     93.64    95.00    107.41  73.89
5        7       95.00     92.58    93.12     97.78  68.06
6        8       95.05    102.99    56.25     99.07  50.00
8        8       84.26     93.10    47.50     18.52  50.83
9        7       90.10     97.55    51.25     88.89  63.61
10       7       80.44     90.20    75.00     91.48  39.72
12       8       97.16    103.71    72.50     93.52  63.33
13       7       91.28     83.53    81.25     99.81  92.22

Perceba que algumas linhas foram removidas

In [45]:
# Uma das funções úteis que o Pandas tem para trabalhar com valores ausentes é a função de preenchimento chamada fillna(). Essa função usa vários parâmetros, de modo que podemos passar um único valor, chamado de valor escalar, para transformar todos os dados ausentes em um único valor

# Se quiséssemos preencher todos os valores ausentes com zero, podemos usar fillna()
df.fillna(0, inplace = True)

    Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0        5       57.14     34.09    64.38     51.48  52.50
1        8       95.05    105.49    67.50     99.07  68.33
2        8       83.70     83.17     0.00     63.15  48.89
3        7        0.00      0.00    49.38    105.93  80.56
4        8       91.32     93.64    95.00    107.41  73.89
..     ...         ...       ...      ...       ...    ...
94       8        0.00    103.71    45.00     93.52  61.94
95       7        0.00     80.54    41.25     93.70  39.72
96       8       89.94    102.77    87.50     90.74  87.78
97       7       95.60     76.13    66.25     99.81  85.56
98       8       63.40     97.37    73.12     72.78  77.22

[99 rows x 6 columns]

In [ ]:
# Também podemos usar o parâmetro na_filter para desativar a filtragem de espaço em branco se o espaço em branco for um valor real de interesse. 
# OBS: Na prática isso é muito raro, pois em dados sem nenhum NAs, passar na_filter = False pode melhorar o desempenho da leitura de um arquivo grande 
# pd.read_csv("arquivo.csv", na_filter = False) 
"""
Quando pedimos isso, estamos falando: Não procure valores ausentes. Leia tudo exatamente como está.”

Ou seja:
Ele não converte strings vazias em NaN
Ele não converte "NA" em NaN
Ele simplesmente carrega os dados como texto bruto
"""

df = pd.read_csv('datasets/log.csv')
df.head(20)

          time    user          video  playback position paused  volume
0   1469974424  cheryl     intro.html                  5  False    10.0
1   1469974454  cheryl     intro.html                  6    NaN     NaN
2   1469974544  cheryl     intro.html                  9    NaN     NaN
3   1469974574  cheryl     intro.html                 10    NaN     NaN
4   1469977514     bob     intro.html                  1    NaN     NaN
5   1469977544     bob     intro.html                  1    NaN     NaN
6   1469977574     bob     intro.html                  1    NaN     NaN
7   1469977604     bob     intro.html                  1    NaN     NaN
8   1469974604  cheryl     intro.html                 11    NaN     NaN
9   1469974694  cheryl     intro.html                 14    NaN     NaN
10  1469974724  cheryl     intro.html                 15    NaN     NaN
11  1469974454     sue  advanced.html                 24    NaN     NaN
12  1469974524     sue  advanced.html                 25    NaN     NaN
13  1469974424     sue  advanced.html                 23  False    10.0
14  1469974554     sue  advanced.html                 26    NaN     NaN
15  1469974624     sue  advanced.html                 27    NaN     NaN
16  1469974654     sue  advanced.html                 28    NaN     5.0
17  1469974724     sue  advanced.html                 29    NaN     NaN
18  1469974484  cheryl     intro.html                  7    NaN     NaN
19  1469974514  cheryl     intro.html                  8    NaN     NaN

In [47]:
# Vamos setar o index com base na coluna 'time'
df = df.set_index('time')

# Vamos ordenar com base no index, pois ao mudar o index, vai ficar desordenado
df = df.sort_index()
df.head(20)

              user          video  playback position paused  volume
time
1469974424  cheryl     intro.html                  5  False    10.0
1469974424     sue  advanced.html                 23  False    10.0
1469974454     sue  advanced.html                 24    NaN     NaN
1469974454  cheryl     intro.html                  6    NaN     NaN
1469974484  cheryl     intro.html                  7    NaN     NaN
1469974514  cheryl     intro.html                  8    NaN     NaN
1469974524     sue  advanced.html                 25    NaN     NaN
1469974544  cheryl     intro.html                  9    NaN     NaN
1469974554     sue  advanced.html                 26    NaN     NaN
1469974574  cheryl     intro.html                 10    NaN     NaN
1469974604  cheryl     intro.html                 11    NaN     NaN
1469974624     sue  advanced.html                 27    NaN     NaN
1469974634  cheryl     intro.html                 12    NaN     NaN
1469974654     sue  advanced.html                 28    NaN     5.0
1469974664  cheryl     intro.html                 13    NaN     NaN
1469974694  cheryl     intro.html                 14    NaN     NaN
1469974724  cheryl     intro.html                 15    NaN     NaN
1469974724     sue  advanced.html                 29    NaN     NaN
1469974754     sue  advanced.html                 30    NaN     NaN
1469974824     sue  advanced.html                 31    NaN     NaN

In [54]:
# Se observarmos atentamente a saída, perceberemos que o índice não é realmente único. Parece que dois usuários conseguem usar o sistema ao mesmo tempo. 
# Nesse caso, vamos redefinir o índice e usar uma indexação multi-nível sobre pontualidade e o usuário

df.reset_index(inplace = True)
df.set_index(['time', 'user'], inplace = True)
df.sort_index(inplace = True)
df

                           video  playback position paused  volume
time       user
1469974424 cheryl     intro.html                  5  False    10.0
           sue     advanced.html                 23  False    10.0
1469974454 cheryl     intro.html                  6    NaN     NaN
           sue     advanced.html                 24    NaN     NaN
1469974484 cheryl     intro.html                  7    NaN     NaN
1469974514 cheryl     intro.html                  8    NaN     NaN
1469974524 sue     advanced.html                 25    NaN     NaN
1469974544 cheryl     intro.html                  9    NaN     NaN
1469974554 sue     advanced.html                 26    NaN     NaN
1469974574 cheryl     intro.html                 10    NaN     NaN
1469974604 cheryl     intro.html                 11    NaN     NaN
1469974624 sue     advanced.html                 27    NaN     NaN
1469974634 cheryl     intro.html                 12    NaN     NaN
1469974654 sue     advanced.html                 28    NaN     5.0
1469974664 cheryl     intro.html                 13    NaN     NaN
1469974694 cheryl     intro.html                 14    NaN     NaN
1469974724 cheryl     intro.html                 15    NaN     NaN
           sue     advanced.html                 29    NaN     NaN
1469974754 sue     advanced.html                 30    NaN     NaN
1469974824 sue     advanced.html                 31    NaN     NaN
1469974854 sue     advanced.html                 32    NaN     NaN
1469974924 sue     advanced.html                 33    NaN     NaN
1469977424 bob        intro.html                  1   True    10.0
1469977454 bob        intro.html                  1    NaN     NaN
1469977484 bob        intro.html                  1    NaN     NaN
1469977514 bob        intro.html                  1    NaN     NaN
1469977544 bob        intro.html                  1    NaN     NaN
1469977574 bob        intro.html                  1    NaN     NaN
1469977604 bob        intro.html                  1    NaN     NaN
1469977634 bob        intro.html                  1    NaN     NaN
1469977664 bob        intro.html                  1    NaN     NaN
1469977694 bob        intro.html                  1    NaN     NaN
1469977724 bob        intro.html                  1    NaN     NaN

In [56]:
# Agora que temos os dados indexados e classificados adequadamente, podemos preencher os dados ausentes usando ffill. 
# É bom lembrar que, ao lidar com valores ausentes, você pode lidar com colunas indivudais ou conjuntos de colunass projetando-os para que não precise corrigir todos os valores ausentes em um comando. 

df = df.ffill()
df.head()

                           video  playback position paused  volume
time       user
1469974424 cheryl     intro.html                  5  False    10.0
           sue     advanced.html                 23  False    10.0
1469974454 cheryl     intro.html                  6  False    10.0
           sue     advanced.html                 24  False    10.0
1469974484 cheryl     intro.html                  7  False    10.0

##### Essa função ffill() faz:
- Ele preenche valores ausentes com o último valor válido acima.

Já a fillna() preenche com um valor especificado.

In [58]:
# Também podemos fazer um preenchimento personalizado para substituir os valores com a função replace(). Ela permite a substituição de várias abordagens, valor para valor, lista, dicionário, regex, então vamos gerar um exemplo simples.
df = pd.DataFrame({'A': [1, 1, 2, 3, 4], 
                   'B': [3, 6, 3, 8, 9],
                   'C': ['a', 'b', 'c', 'd', 'e']})
df

   A  B  C
0  1  3  a
1  1  6  b
2  2  3  c
3  3  8  d
4  4  9  e

In [61]:
# Poderíamos substituir aquele por 100. Então vamos tentar a abordagem de valor para valor 
# Vamos passar na função replace() primeiro o valor que vamos substituir e depois o valor que entrará no lugar.
df.replace(1, 100, inplace = True)

     A  B  C
0  100  3  a
1  100  6  b
2    2  3  c
3    3  8  d
4    4  9  e

In [62]:
# Agora vamos mudar tanto o 100 quanto o 3 para 103 e 300
df.replace([100, 3], [103, 300])

     A    B  C
0  103  300  a
1  103    6  b
2    2  300  c
3  300    8  d
4    4    9  e

In [64]:
# A substituição do Pandas também suporta regex
df = pd.read_csv('datasets/log.csv')
df

          time    user          video  playback position paused  volume
0   1469974424  cheryl     intro.html                  5  False    10.0
1   1469974454  cheryl     intro.html                  6    NaN     NaN
2   1469974544  cheryl     intro.html                  9    NaN     NaN
3   1469974574  cheryl     intro.html                 10    NaN     NaN
4   1469977514     bob     intro.html                  1    NaN     NaN
5   1469977544     bob     intro.html                  1    NaN     NaN
6   1469977574     bob     intro.html                  1    NaN     NaN
7   1469977604     bob     intro.html                  1    NaN     NaN
8   1469974604  cheryl     intro.html                 11    NaN     NaN
9   1469974694  cheryl     intro.html                 14    NaN     NaN
10  1469974724  cheryl     intro.html                 15    NaN     NaN
11  1469974454     sue  advanced.html                 24    NaN     NaN
12  1469974524     sue  advanced.html                 25    NaN     NaN
13  1469974424     sue  advanced.html                 23  False    10.0
14  1469974554     sue  advanced.html                 26    NaN     NaN
15  1469974624     sue  advanced.html                 27    NaN     NaN
16  1469974654     sue  advanced.html                 28    NaN     5.0
17  1469974724     sue  advanced.html                 29    NaN     NaN
18  1469974484  cheryl     intro.html                  7    NaN     NaN
19  1469974514  cheryl     intro.html                  8    NaN     NaN
20  1469974754     sue  advanced.html                 30    NaN     NaN
21  1469974824     sue  advanced.html                 31    NaN     NaN
22  1469974854     sue  advanced.html                 32    NaN     NaN
23  1469974924     sue  advanced.html                 33    NaN     NaN
24  1469977424     bob     intro.html                  1   True    10.0
25  1469977454     bob     intro.html                  1    NaN     NaN
26  1469977484     bob     intro.html                  1    NaN     NaN
27  1469977634     bob     intro.html                  1    NaN     NaN
28  1469977664     bob     intro.html                  1    NaN     NaN
29  1469974634  cheryl     intro.html                 12    NaN     NaN
30  1469974664  cheryl     intro.html                 13    NaN     NaN
31  1469977694     bob     intro.html                  1    NaN     NaN
32  1469977724     bob     intro.html                  1    NaN     NaN

In [65]:
# Para substituir usando regex, criamos o primeiro parâmetro para substituir o padrão regex que queremos substituir, o segundo parâmetro, o valor que queremos emitir em uma correspondência, e então passamos um terceiro parâmetro que diz apenas que regex é igual a true. 

df.replace(to_replace = '.*.html$', value = 'webpage', regex = True)

          time    user    video  playback position paused  volume
0   1469974424  cheryl  webpage                  5  False    10.0
1   1469974454  cheryl  webpage                  6    NaN     NaN
2   1469974544  cheryl  webpage                  9    NaN     NaN
3   1469974574  cheryl  webpage                 10    NaN     NaN
4   1469977514     bob  webpage                  1    NaN     NaN
5   1469977544     bob  webpage                  1    NaN     NaN
6   1469977574     bob  webpage                  1    NaN     NaN
7   1469977604     bob  webpage                  1    NaN     NaN
8   1469974604  cheryl  webpage                 11    NaN     NaN
9   1469974694  cheryl  webpage                 14    NaN     NaN
10  1469974724  cheryl  webpage                 15    NaN     NaN
11  1469974454     sue  webpage                 24    NaN     NaN
12  1469974524     sue  webpage                 25    NaN     NaN
13  1469974424     sue  webpage                 23  False    10.0
14  1469974554     sue  webpage                 26    NaN     NaN
15  1469974624     sue  webpage                 27    NaN     NaN
16  1469974654     sue  webpage                 28    NaN     5.0
17  1469974724     sue  webpage                 29    NaN     NaN
18  1469974484  cheryl  webpage                  7    NaN     NaN
19  1469974514  cheryl  webpage                  8    NaN     NaN
20  1469974754     sue  webpage                 30    NaN     NaN
21  1469974824     sue  webpage                 31    NaN     NaN
22  1469974854     sue  webpage                 32    NaN     NaN
23  1469974924     sue  webpage                 33    NaN     NaN
24  1469977424     bob  webpage                  1   True    10.0
25  1469977454     bob  webpage                  1    NaN     NaN
26  1469977484     bob  webpage                  1    NaN     NaN
27  1469977634     bob  webpage                  1    NaN     NaN
28  1469977664     bob  webpage                  1    NaN     NaN
29  1469974634  cheryl  webpage                 12    NaN     NaN
30  1469974664  cheryl  webpage                 13    NaN     NaN
31  1469977694     bob  webpage                  1    NaN     NaN
32  1469977724     bob  webpage                  1    NaN     NaN