# Manipulação de DataFrame

In [2]:
# Importando a biblioteca
import pandas as pd

# Lendo o arquivo
df = pd.read_csv('datasets/presidents.csv')

df.head()

,#,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age
0,1,George Washington,"Feb 22, 1732[a]","57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days"
1,2,John Adams,"Oct 30, 1735[a]","61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days"
2,3,Thomas Jefferson,"Apr 13, 1743[a]","57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days"
3,4,James Madison,"Mar 16, 1751[a]","57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days"
4,5,James Monroe,"Apr 28, 1758","58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days"

In [3]:
# Vamos colocar o index para a coluna '#'
df.set_index('#', inplace = True)
df.head()

,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age
#,,,,,,,
1,George Washington,"Feb 22, 1732[a]","57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days"
2,John Adams,"Oct 30, 1735[a]","61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days"
3,Thomas Jefferson,"Apr 13, 1743[a]","57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days"
4,James Madison,"Mar 16, 1751[a]","57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days"
5,James Monroe,"Apr 28, 1758","58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days"

Temos agumas notas de rodapé na coluna 'born', então vamos tirar essas notas, pois elas podem causar problemas. Além disso, também vamos ajustar os presidentes em primeiro nome e sobrenome.

In [4]:
# 1° Forma: 
# Vamos copiar a coluna de president
df['Primeiro nome'] = df['President']

# Agoram podemos modificar a nova coluna com replace() 
df['Primeiro nome'] = df['Primeiro nome'].replace('\s[\w]*', '', regex = True)
df.head()

,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age,Primeiro nome
#,,,,,,,,
1,George Washington,"Feb 22, 1732[a]","57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George
2,John Adams,"Oct 30, 1735[a]","61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days",John
3,Thomas Jefferson,"Apr 13, 1743[a]","57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days",Thomas
4,James Madison,"Mar 16, 1751[a]","57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days",James
5,James Monroe,"Apr 28, 1758","58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days",James

Isso que fizemos funciona, porém é meio inadequado e é lento, pois tivemos que fazer uma cópia completa da coluna antes e depois atualizar as strings.

In [5]:
# 2° Forma:
# Forma mais genérica, que é a função apply()

# Removendo a coluna que criamos
del df['Primeiro nome']

# A função apply() em um DataFrame pega alguma função arbitrária que você codificou e a aplica a uma série, a uma única coluna ou ao DataFrame total, de forma iterativa
def separa_nome(linha: pd.Series):
    # Cada chamada dessa função recebe uma linha do DataFrame, a qual é passada como uma Série
    # Vamos extrair o primeiro nome e criar uma nova entrada para a série
    linha['Primeiro nome'] = str(linha['President']).split()[0]
    linha['Sobrenome'] = str(linha['President']).split()[-1]

    return linha

# Agora aplicamos isso ao DataFrame indicando que queremos aplicar nas colunas
df = df.apply(separa_nome, axis = 1)
df.head(10)

,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age,Primeiro nome,Sobrenome
#,,,,,,,,,
1,George Washington,"Feb 22, 1732[a]","57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George,Washington
2,John Adams,"Oct 30, 1735[a]","61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days",John,Adams
3,Thomas Jefferson,"Apr 13, 1743[a]","57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days",Thomas,Jefferson
4,James Madison,"Mar 16, 1751[a]","57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days",James,Madison
5,James Monroe,"Apr 28, 1758","58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days",James,Monroe
6,John Quincy Adams,"Jul 11, 1767","57 years, 236 daysMar 4, 1825","61 years, 236 daysMar 4, 1829","18 years, 356 days","Feb 23, 1848","80 years, 227 days",John,Adams
7,Andrew Jackson,"Mar 15, 1767","61 years, 354 daysMar 4, 1829","69 years, 354 daysMar 4, 1837","8 years, 96 days","Jun 8, 1845","78 years, 85 days",Andrew,Jackson
8,Martin Van Buren,"Dec 5, 1782","54 years, 89 daysMar 4, 1837","58 years, 89 daysMar 4, 1841","21 years, 142 days","Jul 24, 1862","79 years, 231 days",Martin,Buren
9,William H. Harrison,"Feb 9, 1773","68 years, 23 daysMar 4, 1841","68 years, 54 days Apr 4, 1841[b]",NaN,"Apr 4, 1841","68 years, 54 days",William,Harrison
10,John Tyler,"Mar 29, 1790","51 years, 6 daysApr 4, 1841","54 years, 340 daysMar 4, 1845","16 years, 320 days","Jan 18, 1862","71 years, 295 days",John,Tyler

In [6]:
# 3° Forma: 

# Removendo as colunas que criamos
df.drop(['Primeiro nome', 'Sobrenome'], axis = 1, inplace = True)

# Vamos usar a função extract(), pois ela pega expressões regulares (regex) como entrada, atribuindo o valor desejado de grupos de captura que correspondem às colunas de saída que estamos interessados
nomes = df['President'].str.extract('(?P<Primeiro_nome>^[\w]*)(?:.*\s)(?P<Sobrenome>[\w]*$)')
nomes

   Primeiro_nome   Sobrenome
#
1         George  Washington
2           John       Adams
3         Thomas   Jefferson
4          James     Madison
5          James      Monroe
6           John       Adams
7         Andrew     Jackson
8         Martin       Buren
9        William    Harrison
10          John       Tyler
11         James        Polk
12       Zachary      Taylor
13       Millard    Fillmore
14      Franklin      Pierce
15         James    Buchanan
16       Abraham     Lincoln
17        Andrew     Johnson
18       Ulysses       Grant
19    Rutherford       Hayes
20         James    Garfield
21       Chester      Arthur
22        Grover   Cleveland
23      Benjamin    Harrison
24        Grover   Cleveland
25       William    McKinley
26      Theodore   Roosevelt
27       William        Taft
28       Woodrow      Wilson
29        Warren     Harding
30        Calvin    Coolidge
31       Herbert      Hoover
32      Franklin   Roosevelt
33         Harry      Truman
34        Dwight  Eisenhower
35          John     Kennedy
36        Lyndon     Johnson
37       Richard       Nixon
38        Gerald        Ford
39         Jimmy      Carter
40        Ronald      Reagan
41        George        Bush
42          Bill     Clinton
43        George        Bush
44        Barack       Obama

OBS: Em regex, o nome do grupo não pode ter espaços

In [7]:
# Agora, basta passar isso para o DataFrame
df['Primeiro nome'] = nomes['Primeiro_nome']
df['Sobrenome'] = nomes['Sobrenome']
df.head()

,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age,Primeiro nome,Sobrenome
#,,,,,,,,,
1,George Washington,"Feb 22, 1732[a]","57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George,Washington
2,John Adams,"Oct 30, 1735[a]","61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days",John,Adams
3,Thomas Jefferson,"Apr 13, 1743[a]","57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days",Thomas,Jefferson
4,James Madison,"Mar 16, 1751[a]","57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days",James,Madison
5,James Monroe,"Apr 28, 1758","58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days",James,Monroe

Agora vamos olhar para a parte do 'Born'

In [8]:
# Primeiro, vamos nos livrar de tudo que não está no padrão dia, mês, ano
df['Born'] = df['Born'].str.extract('(?P<Data>[\w]{3}\s[\d]{1,2}\,\s[\d]{4})(?:\[.*\])?')
df['Born']

#
1     Feb 22, 1732
2     Oct 30, 1735
3     Apr 13, 1743
4     Mar 16, 1751
5     Apr 28, 1758
6     Jul 11, 1767
7     Mar 15, 1767
8      Dec 5, 1782
9      Feb 9, 1773
10    Mar 29, 1790
11     Nov 2, 1795
12    Nov 24, 1784
13     Jan 7, 1800
14    Nov 23, 1804
15    Apr 23, 1791
16    Feb 12, 1809
17    Dec 29, 1808
18    Apr 27, 1822
19     Oct 4, 1822
20    Nov 19, 1831
21     Oct 5, 1829
22    Mar 18, 1837
23    Aug 20, 1833
24    Mar 18, 1837
25    Jan 29, 1843
26    Oct 27, 1858
27    Sep 15, 1857
28    Dec 28, 1856
29     Nov 2, 1865
30     Jul 4, 1872
31    Aug 10, 1874
32    Jan 30, 1882
33     May 8, 1884
34    Oct 14, 1890
35    May 29, 1917
36    Aug 27, 1908
37     Jan 9, 1913
38    Jul 14, 1913
39     Oct 1, 1924
40     Feb 6, 1911
41    Jun 12, 1924
42    Aug 19, 1946
43     Jul 6, 1946
44     Aug 4, 1961
Name: Born, dtype: str

OBS: As funções '.str.' são vetorizadas

In [10]:
# Perceba que o tipo dessa coluna é "str", mas o Pandas tem funcionalidades interessantes para lidar com data/hora

# Vamos transformar a str em data/hora 
df['Born'] = pd.to_datetime(df['Born'])
df['Born'].head()

#
1   1732-02-22
2   1735-10-30
3   1743-04-13
4   1751-03-16
5   1758-04-28
Name: Born, dtype: datetime64[us]

Isso faria com que o processamento subsequente nos dados relacionados a datas, como conseguir todos os presidentes nascidos em determinado período, se torne muito mais fácil