# Concatenando DataFrames

Podemos pensar que mesclar é como uma união horizontal, o que significa que unimos valores semelhantes em uma coluna encontrada em dois DataFrames. Já concatenar, é unir verticalmente, o que significa que colocamos DataFrames na parte superior ou inferior um do outro.

#### Diferença entre concatenar e realizar o merge de DataFrames

- merge() → junta por chave (tipo JOIN em banco de dados)
- concat() → apenas cola DataFrames (empilha ou coloca lado a lado)

In [1]:
# importando a biblioteca
import pandas as pd

In [5]:
# Vamos entender isso a partir de um exemplo:
# Temos três DataFrames representando registros de alunos em anos diferentes:
# 2024, 2025 e 2026.
# Podemos considerar que cada ano foi originalmente armazenado em um CSV separado,
# mas todos possuem exatamente as mesmas colunas:
# ID_Aluno, Nome, Curso, Nota_Media e Ano.

# Dataset 2024
alunos_2024 = pd.DataFrame({
    "ID_Aluno": [1, 2, 3],
    "Nome": ["Ana", "Bruno", "Carlos"],
    "Curso": ["Engenharia", "Direito", "Medicina"],
    "Nota_Media": [8.5, 7.2, 9.1],
    "Ano": [2024, 2024, 2024]
}).set_index('ID_Aluno')

# Dataset 2025
alunos_2025 = pd.DataFrame({
    "ID_Aluno": [4, 5, 6],
    "Nome": ["Daniela", "Eduardo", "Fernanda"],
    "Curso": ["Engenharia", "Direito", "Medicina"],
    "Nota_Media": [8.9, 6.8, 9.3],
    "Ano": [2025, 2025, 2025]
}).set_index('ID_Aluno')

# Dataset 2026
alunos_2026 = pd.DataFrame({
    "ID_Aluno": [7, 8, 9],
    "Nome": ["Gabriel", "Helena", "Igor"],
    "Curso": ["Engenharia", "Direito", "Medicina"],
    "Nota_Media": [7.5, 8.1, 8.7],
    "Ano": [2026, 2026, 2026]
}).set_index('ID_Aluno')

# Visualização
display(alunos_2024)
display(alunos_2025)
display(alunos_2026)

            Nome       Curso  Nota_Media   Ano
ID_Aluno
1            Ana  Engenharia         8.5  2024
2          Bruno     Direito         7.2  2024
3         Carlos    Medicina         9.1  2024

              Nome       Curso  Nota_Media   Ano
ID_Aluno
4          Daniela  Engenharia         8.9  2025
5          Eduardo     Direito         6.8  2025
6         Fernanda    Medicina         9.3  2025

             Nome       Curso  Nota_Media   Ano
ID_Aluno
7         Gabriel  Engenharia         7.5  2026
8          Helena     Direito         8.1  2026
9            Igor    Medicina         8.7  2026

##### OBS: Não precisa ter as mesmas quantidade de colunas nem os mesmos nomes para concatenar

In [9]:
# Como a estrutura é idêntica entre os anos, podemos combinar
# todos os registros utilizando concatenação vertical (axis = 0),
# empilhando as linhas de cada ano para formar um único dataset
# consolidado com todos os alunos ao longo do tempo.
#
# Isso é equivalente a juntar os três arquivos CSV em uma única tabela.

df_final = pd.concat([alunos_2024, alunos_2025, alunos_2026])
display(df_final)

              Nome       Curso  Nota_Media   Ano
ID_Aluno
1              Ana  Engenharia         8.5  2024
2            Bruno     Direito         7.2  2024
3           Carlos    Medicina         9.1  2024
4          Daniela  Engenharia         8.9  2025
5          Eduardo     Direito         6.8  2025
6         Fernanda    Medicina         9.3  2025
7          Gabriel  Engenharia         7.5  2026
8           Helena     Direito         8.1  2026
9             Igor    Medicina         8.7  2026

Perceba que agora temos um único DataFrame com todas as informações dos três DataFrames de alunos juntos.

In [10]:
# Também podemos utilizar um parâmetro para uma melhor organização dos DataFrames, separando em chaves de anos.

df_final = pd.concat([alunos_2024, alunos_2025, alunos_2026], keys = ['2024', '2025', '2026'])
display(df_final)

                   Nome       Curso  Nota_Media   Ano
     ID_Aluno
2024 1              Ana  Engenharia         8.5  2024
     2            Bruno     Direito         7.2  2024
     3           Carlos    Medicina         9.1  2024
2025 4          Daniela  Engenharia         8.9  2025
     5          Eduardo     Direito         6.8  2025
     6         Fernanda    Medicina         9.3  2025
2026 7          Gabriel  Engenharia         7.5  2026
     8           Helena     Direito         8.1  2026
     9             Igor    Medicina         8.7  2026

In [12]:
# Ou ainda, nomear essa coluna de índice:

df_final = pd.concat([alunos_2024, alunos_2025, alunos_2026], keys = ['2024', '2025', '2026'], names = ['Ano', 'ID_Aluno'])
display(df_final)

                   Nome       Curso  Nota_Media   Ano
Ano  ID_Aluno
2024 1              Ana  Engenharia         8.5  2024
     2            Bruno     Direito         7.2  2024
     3           Carlos    Medicina         9.1  2024
2025 4          Daniela  Engenharia         8.9  2025
     5          Eduardo     Direito         6.8  2025
     6         Fernanda    Medicina         9.3  2025
2026 7          Gabriel  Engenharia         7.5  2026
     8           Helena     Direito         8.1  2026
     9             Igor    Medicina         8.7  2026

In [14]:
# Podemos concatenar de forma horizontal também

# Vamos criar um novo exemplo: 
# DF 1
df_pessoal = pd.DataFrame({
    "Nome": ["Ana", "Bruno", "Carlos"],
    "Idade": [20, 22, 21]
})

# DF 2
df_academico = pd.DataFrame({
    "Curso": ["Engenharia", "Direito", "Medicina"],
    "Nota_Media": [8.5, 7.2, 9.1]
})

display(df_pessoal)
display(df_academico)

     Nome  Idade
0     Ana     20
1   Bruno     22
2  Carlos     21

        Curso  Nota_Media
0  Engenharia         8.5
1     Direito         7.2
2    Medicina         9.1

In [16]:
# Concatenando horizontalmente

df_final = pd.concat([df_pessoal, df_academico], axis = 1)
display(df_final)

     Nome  Idade       Curso  Nota_Media
0     Ana     20  Engenharia         8.5
1   Bruno     22     Direito         7.2
2  Carlos     21    Medicina         9.1