# Expressões idiomáticas sobre Pandas

Programadores de Python, geralmente sugerem que há muitas maneiras pelas quais a linguagem pode ser usada para resolver um problema específico, mas que algumas são mais apropriadas do que outras. Dessa forma, as melhores soluções são conhecidas como Python idiomático, e há muitos exemplos excelentes no StackOverflow ou em outros sites.

Como uma espécie de sub-linguagem dentro do Python, o Pandas tem seu próprio conjunto de expressões idiomáticas. Já mencionamos algumas delas, como usar vetorização sempre que possível ao invés de loops iterativos. <br>
Vários desenvolvedores e usuários da comunidade Pandas usaram o termo __pandorable__ (pandorável) para esses idiomas. <br>
Sendo assim, vamos ver alguns dos principais recursos de como podemos tornar o código mais pandorável.

In [2]:
# Bibliotecas 
import pandas as pd
import numpy as np

# Vamos trazer algumas funcionalidades de temporização 
import timeit 

# Vamos ler o arquivo de dados CSV 
df = pd.read_csv('datasets/census.csv')
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

##### 1 - Encadeamento de Métodos

In [ ]:
# A primeira das expressões idiomáticas do Pandas é o chamado de encadeamento de métodos (method chaining).
# A ideia geral por trás do encadeamento de métodos é que cada método em um objeto retorna uma referência a esse objeto. A beleza disso é que podemos condensar muitas operações diferentes em um DataFrame, por exemplo, em uma linha ou pelo menos uma declaração de código. 

# Vamos a uma excelente maneira de como escrever código com encadeamento de métodos. Neste código, vamos retirar os nomes dos estados e das cidades como um índice múltiplo, e sera feito apenas para dados que tenham um nível resumido de 50, que no conjunto de dados em questão são dados em nível de condado. Além disso, vamos renomear a coluna dois apenas para torná-la um pouco mais legível. 

df = (df[df['SUMLEV'] == 50]
      .dropna()
      .set_index(['STNAME', 'CTYNAME'])
      .rename(columns = {'ESTIMATESBASE2010': 'Estimates Base 2010'}))

# OBS: Poderíamos colocar da seguinte maneira: 
#
# df = df.where(df['SUMLEV'] == 50).dropna()...
#
# Porém, o método .where() mantém o tamanho original do DataFrame, substituindo por NaN as linhas onde a condição não é satisfeita. Em seguida, o .dropna() remove essas linhas.
# De forma direta, como foi feito, é realizada diretamente a filtragem das linhas que satisfazem a condição, e o .dropna() é para apagar dados faltantes. 

display(df.head())

                        SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME  CTYNAME
Alabama Autauga County      50       3         6      1       1
        Baldwin County      50       3         6      1       3
        Barbour County      50       3         6      1       5
        Bibb County         50       3         6      1       7
        Blount County       50       3         6      1       9

                        CENSUS2010POP  Estimates Base 2010  POPESTIMATE2010  \
STNAME  CTYNAME
Alabama Autauga County          54571                54571            54660
        Baldwin County         182265               182265           183193
        Barbour County          27457                27457            27341
        Bibb County             22915                22919            22861
        Blount County           57322                57322            57373

                        POPESTIMATE2011  POPESTIMATE2012  ...  \
STNAME  CTYNAME                                           ...
Alabama Autauga County            55253            55175  ...
        Baldwin County           186659           190396  ...
        Barbour County            27226            27159  ...
        Bibb County               22733            22642  ...
        Blount County             57711            57776  ...

                        RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  \
STNAME  CTYNAME
Alabama Autauga County          7.242091         -2.915927         -3.012349
        Baldwin County         14.832960         17.647293         21.845705
        Barbour County         -4.728132         -2.500690         -7.056824
        Bibb County            -5.527043         -5.068871         -6.201001
        Blount County           1.807375         -1.177622         -1.748766

                        RDOMESTICMIG2014  RDOMESTICMIG2015  RNETMIG2011  \
STNAME  CTYNAME
Alabama Autauga County          2.265971         -2.530799     7.606016
        Baldwin County         19.243287         17.197872    15.844176
        Barbour County         -3.904217        -10.543299    -4.874741
        Bibb County            -0.177537          0.177258    -5.088389
        Blount County          -2.062535         -1.369970     1.859511

                        RNETMIG2012  RNETMIG2013  RNETMIG2014  RNETMIG2015
STNAME  CTYNAME
Alabama Autauga County    -2.626146    -2.722002     2.592270    -2.187333
        Baldwin County    18.559627    22.727626    20.317142    18.293499
        Barbour County    -2.758113    -7.167664    -3.978583   -10.543299
        Bibb County       -4.363636    -5.403729     0.754533     1.107861
        Blount County     -0.848580    -1.402476    -1.577232    -0.884411

[5 rows x 98 columns]

Perceba que para facilitar a leitura, ao invés de escrever tudo em uma linha, a qual ficaria gigante e de difícil percepção sobre o que está ocorrento, podemos colocar tudo dentro de parênteses, isto é:

- (df <br>
&emsp; .método1 <br>
&emsp; .método2 <br>
&emsp; ...)

Dessa forma, estamos dizendo ao Python que vamos estender essa instrução por várias linhas.

In [ ]:
# Aqui está uma maneira mais tradicional e não pandorável de escrever isso:
# OBS: Não há nada de errado com o código em um sentido funcional, porém não é considerado tão pandorável quanto o primeiro exemplo. 

# Vamos ler novamente o CSV
df = pd.read_csv('datasets/census.csv')

# Realizar o uso dos métodos de forma NÃO pandorável
# Usando o operador de indexação sobrecarregado que descarta NaNs 
df = df[df['SUMLEV'] == 50] 

# Em seguida, atualizaremos o DataFrame para obtermos um novo índice e usaremos inplace = True para fazer isso no local. 
df.set_index(['STNAME', 'CTYNAME'], inplace = True)

# Agora, vamos definir o nome da coluna
df.rename(columns = {'ESTIMATESBASE2010': 'Estimates Base 2010'}, inplace = True)

# Vamos visualizar
df.head()

                        SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME  CTYNAME
Alabama Autauga County      50       3         6      1       1
        Baldwin County      50       3         6      1       3
        Barbour County      50       3         6      1       5
        Bibb County         50       3         6      1       7
        Blount County       50       3         6      1       9

                        CENSUS2010POP  Estimates Base 2010  POPESTIMATE2010  \
STNAME  CTYNAME
Alabama Autauga County          54571                54571            54660
        Baldwin County         182265               182265           183193
        Barbour County          27457                27457            27341
        Bibb County             22915                22919            22861
        Blount County           57322                57322            57373

                        POPESTIMATE2011  POPESTIMATE2012  ...  \
STNAME  CTYNAME                                           ...
Alabama Autauga County            55253            55175  ...
        Baldwin County           186659           190396  ...
        Barbour County            27226            27159  ...
        Bibb County               22733            22642  ...
        Blount County             57711            57776  ...

                        RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  \
STNAME  CTYNAME
Alabama Autauga County          7.242091         -2.915927         -3.012349
        Baldwin County         14.832960         17.647293         21.845705
        Barbour County         -4.728132         -2.500690         -7.056824
        Bibb County            -5.527043         -5.068871         -6.201001
        Blount County           1.807375         -1.177622         -1.748766

                        RDOMESTICMIG2014  RDOMESTICMIG2015  RNETMIG2011  \
STNAME  CTYNAME
Alabama Autauga County          2.265971         -2.530799     7.606016
        Baldwin County         19.243287         17.197872    15.844176
        Barbour County         -3.904217        -10.543299    -4.874741
        Bibb County            -0.177537          0.177258    -5.088389
        Blount County          -2.062535         -1.369970     1.859511

                        RNETMIG2012  RNETMIG2013  RNETMIG2014  RNETMIG2015
STNAME  CTYNAME
Alabama Autauga County    -2.626146    -2.722002     2.592270    -2.187333
        Baldwin County    18.559627    22.727626    20.317142    18.293499
        Barbour County    -2.758113    -7.167664    -3.978583   -10.543299
        Bibb County       -4.363636    -5.403729     0.754533     1.107861
        Blount County     -0.848580    -1.402476    -1.577232    -0.884411

[5 rows x 98 columns]

Perceba que obtivemos o mesmo resultado, mas precisamos entender quando a linguagem NÃO está nos ajudando. 

Nesse caso, podemos cronometrar os dois métodos para ver qual deles é executado mais rápido.

In [16]:
# Podemos colocar a abordagem em uma função e passar a função para o timeit para contar o tempo, o número do parâmetro por tempo 

def primeira_abordagem():
    global df

    return (df[df['SUMLEV'] == 50]
      .dropna()
      .set_index(['STNAME', 'CTYNAME'])
      .rename(columns = {'ESTIMATESBASE2010': 'Estimates Base 2010'}))

# Vamos ler novamente o conjunto de dados
df = pd.read_csv('datasets/census.csv')

# Agora vamos apenas executá-lo e cronometrar
timeit.timeit(primeira_abordagem, number = 100) # Vai fazer 100 vezes

0.9558435660000271

In [20]:
# Agora vamso testar a segunda abordagem 

def segunda_abordagem():
    global df

    novo_df = df[df['SUMLEV'] == 50]
    novo_df.set_index(['STNAME', 'CTYNAME'], inplace = True)
    return novo_df.rename(columns = {'ESTIMATESBASE2010': 'Estimates Base 2010'})

# Vamos ler novamente o conjunto de dados
df = pd.read_csv('datasets/census.csv')

# Vamos cronometrar novamente 
timeit.timeit(segunda_abordagem, number = 100)

0.7076940390000175

Perceba que houve um trade off entre tempo e legibilidade, uma vez que a segunda abordagem é ligeiramente mais rápida, porém é menos legível (menos pandorável)

##### 2 - Map

Python possui uma função chamada map(), que é um dos fundamentos da programação funcional na linguagem. Essa função recebe dois argumentos, isto é, uma função e um objeto iterável (como uma lista). Dessa forma, o map() aplica a função a cada elemento do iterável e retorna um novo iterável contendo os resultados dessa aplicação. 

No contexto do Pandas, existe um comportamento semelhante por meio do método applymap(). O applymap() aplica uma função elemento a elemento, ou seja, em cada célula individual de um DataFrame, e o resultado da operação também é um DataFrame com a mesma estrutura, porém com os valores transformados. <br>
Contudo, o applymap() é menos utilizado na prática, pois raramente precisamos aplicar uma função célula por célula. Na maioria dos casos, desejamos aplicar uma transformação em uma coluna inteira ou em uma linha inteira. Além disso, nas versões mais recentes do Pandas, o uso de applymap() vem sendo desencorajado em favor de abordagens mais modernas, como o uso de map() em Series ou operações vetorizadas. <br>
Para esses casos mais comuns, o Pandas oferece o método apply(). Diferentemente do applymap(), o apply() opera sobre uma estrutura maior, o que significa que ele aplica uma função a cada coluna (axis=0) ou a cada linha (axis=1). Sendo assim, a função recebe uma Series inteira como argumento, e não apenas um valor escalar.

In [ ]:
# Vamos a um exemplo com a base de dados do censo novamente. Nesse caso, temos cinco colunas para estimativas populacionais, com cada coluna correspondendo a um ano de estimativas. É bastante razoável querer criar algumas novas colunas para valores mínimos ou máximos, e a função apply é uma maneira fácil de fazer isso. 

# Primeiro, precisamos escrever uma função que receba uma linha específica de dados, encontreum valor mínimo e máximo, e retorne uma nova linha a partir dela. Chamaremos essa função de min_max.

def min_max(linha: pd.Series): 
    # Vamos selecionar apenas as colunas que importam (lembrando que quando passamos uma linha de um DataFrame, ela vem no formato de Série)
    dados = linha[['POPESTIMATE2010',
                   'POPESTIMATE2011',
                   'POPESTIMATE2012',
                   'POPESTIMATE2013',
                   'POPESTIMATE2014',
                   'POPESTIMATE2015',]]
    # print('Dados', dados)

    return pd.Series({'Mínimo': np.min(dados), 'Máximo': np.max(dados)})

In [25]:
# Agora só precisamos chamar a função apply() no DataFrame. 
# Apply() assume a função e o eixo (axis) no qual operar como parâmetros. 

# Atenção importante:
# axis NÃO representa diretamente "linhas" ou "colunas",
# mas sim o eixo ao longo do qual a operação será executada.
#
# axis = 0  → a função será aplicada em cada COLUNA.
# axis = 1  → a função será aplicada em cada LINHA.
#
# Outra forma equivalente de escrever:
# axis = 'index'   → aplica por coluna (mesmo que axis=0)
# axis = 'columns' → aplica por linha (mesmo que axis=1)

df.apply(min_max, axis = 'columns').head()

    Mínimo   Máximo
0  4785161  4858979
1    54660    55347
2   183193   203709
3    26489    27341
4    22512    22861

Perceba que a função retorna uma Série, mas o resultado final é um DataFrame, e isso ocorre, pois a função apply() junta essas séries para cada linha, o que vira um DataFrame

In [31]:
# Não há necessidade de se limitar a retornar um novo objeto de série. Se estivermos fazendo isso como limpeza de dados, provavelmente vamos querer adicionar novos dados ao DataFrame existente.
# Nesse caso, podemos simplesmente pegar os valores da linha e adicionar novas colunas, indicando as pontuações máxima e mínima. 

# Vamos refazer a função min_max()
# Em vez de retornar uma série separada para exibir o mínimo e o máximo, adicionamos duas novas colunas ao DataFrame original para armazenar o mínimo e o máximo.

def min_max(linha: pd.Series):
    # Vamos selecionar apenas as colunas que importam (lembrando que quando passamos uma linha de um DataFrame, ela vem no formato de Série)
    dados = linha[['POPESTIMATE2010',
                   'POPESTIMATE2011',
                   'POPESTIMATE2012',
                   'POPESTIMATE2013',
                   'POPESTIMATE2014',
                   'POPESTIMATE2015',]]
    
    # Criando novas entradas na Série 
    linha['Máximo'] = np.max(dados)
    linha['Mínimo'] = np.min(dados)
    
    return linha

df.apply(min_max, axis = 'columns').head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,Máximo,Mínimo
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594,4858979,4785161
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333,55347,54660
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499,203709,183193
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299,27341,26489
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861,22861,22512

In [33]:
# Vamos fazer isso agora coma função lambda. 

linhas = ['POPESTIMATE2010',
        'POPESTIMATE2011',
        'POPESTIMATE2012',
        'POPESTIMATE2013',
        'POPESTIMATE2014',
        'POPESTIMATE2015',]

# Agora vamos aplicar em todo o DataFrame com a função lambda
df.apply(lambda x: np.max(x[linhas]), axis = 1).head()

0    4858979
1      55347
2     203709
3      27341
4      22861
dtype: int64

A beleza da função apply() é a flexibilidade para fazer qualquer manipulação que desejarmos, já que a função que passamos para a apply() pode ser qualquer função personalizada.

In [8]:
# Vamos supor que queremos dividir os estados em quatro categorias (nordeste, centro-oeste, sul e oeste). Podemos escrever uma função personalizada que retorne essa região com base nas informações do estado e das regiões estaduais.

def get_estado_regiao(x: str): 
    nordeste = ['Connecticut', 'Maine', 'Massachusetts', 'New Hampshire', 
                 'Rhode Island','Vermont','New York','New Jersey','Pennsylvania']
    centro_oeste = ['Illinois','Indiana','Michigan','Ohio','Wisconsin','Iowa',
               'Kansas','Minnesota','Missouri','Nebraska','North Dakota',
               'South Dakota']
    sul = ['Delaware','Florida','Georgia','Maryland','North Carolina',
             'South Carolina','Virginia','District of Columbia','West Virginia',
             'Alabama','Kentucky','Mississippi','Tennessee','Arkansas',
             'Louisiana','Oklahoma','Texas']
    oeste = ['Arizona','Colorado','Idaho','Montana','Nevada','New Mexico','Utah',
            'Wyoming','Alaska','California','Hawaii','Oregon','Washington']
    
    if x in nordeste:
        return 'Nordeste'

    elif x in centro_oeste:
        return 'Centro-Oeste'
    
    elif x in sul:
        return 'Sul'
    
    elif x in centro_oeste: 
        return 'Oeste'
    
    else:
        return '0'


# Agora vamos usar a função apply()
df['Região_estado'] = df['STNAME'].apply(lambda x: get_estado_regiao(x))

df[['STNAME', 'Região_estado']].head()

    STNAME Região_estado
0  Alabama           Sul
1  Alabama           Sul
2  Alabama           Sul
3  Alabama           Sul
4  Alabama           Sul

Tarefinha: Analise algumas das perguntas mais populares sobre Pandas no Stack Overflow e observe como alguns dos autores mais experientes respondem a essas perguntas.