# Expressões idiomáticas sobre Pandas

Programadores de Python, geralmente sugerem que há muitas maneiras pelas quais a linguagem pode ser usada para resolver um problema específico, mas que algumas são mais apropriadas do que outras. Dessa forma, as melhores soluções são conhecidas como Python idiomático, e há muitos exemplos excelentes no StackOverflow ou em outros sites.

Como uma espécie de sub-linguagem dentro do Python, o Pandas tem seu próprio conjunto de expressões idiomáticas. Já mencionamos algumas delas, como usar vetorização sempre que possível ao invés de loops iterativos. <br>
Vários desenvlvedores e usuários da comunidade Pandas usaram o termo __pandorable__ (pandorável) para esses idiomas. <br>
Sendo assim, vamos ver alguns dos principais recursos de como podemos tornar o código mais pandorável.

In [10]:
# Bibliotecas 
import pandas as pd
import numpy as np

# Vamos trazer algumas funcionalidades de temporização 
import timeit 

# Vamos ler o arquivo de dados CSV 
df = pd.read_csv('datasets/census.csv')
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

##### 1 - Encadeamento de Métodos

In [11]:
# A primeira das expressões idiomáticas do Pandas é o chamado de encadeamento de métodos (method chaining).
# A ideia geral por trás do encadeamento de métodos é que cada método em um objeto retorna uma referência a esse objeto. A beleza disso é que podemos condensar muitas operações diferentes em um DataFrame, por exemplo, em uma linha ou pelo menos uma declaração de código. 

# Vamos a uma excelente maneira de como escrever código com encadeamento de métodos. Neste código, vamos retirar os nomes dos estados e das cidades como um índice múltiplo, e sera feito apenas para dados quetenham um nível resumido de 50, que no conjunto de dados em questão são dados em nível de condado. Além disso, vamos renomear a coluna dois apenas para torná-la um pouco mais legível. 

df = (df[df['SUMLEV'] == 50]
      .dropna()
      .set_index(['STNAME', 'CTYNAME'])
      .rename(columns = {'ESTIMATESBASE2010': 'Estimates Base 2010'}))

# OBS: Poderíamos colocar da seguinte maneira: 
#
# df = df.where(df['SUMLEV'] == 50).dropna()...
#
# Porém, o método .where() mantém o tamanho original do DataFrame, substituindo por NaN as linhas onde a condição não é satisfeita. Em seguida, o .dropna() remove essas linhas.
# De forma direta, como foi feito, é realizada diretamente a filtragem das linhas que satisfazem a condição, e o .dropna() é para apagar dados faltantes. 

display(df.head())

                        SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME  CTYNAME
Alabama Autauga County      50       3         6      1       1
        Baldwin County      50       3         6      1       3
        Barbour County      50       3         6      1       5
        Bibb County         50       3         6      1       7
        Blount County       50       3         6      1       9

                        CENSUS2010POP  Estimates Base 2010  POPESTIMATE2010  \
STNAME  CTYNAME
Alabama Autauga County          54571                54571            54660
        Baldwin County         182265               182265           183193
        Barbour County          27457                27457            27341
        Bibb County             22915                22919            22861
        Blount County           57322                57322            57373

                        POPESTIMATE2011  POPESTIMATE2012  ...  \
STNAME  CTYNAME                                           ...
Alabama Autauga County            55253            55175  ...
        Baldwin County           186659           190396  ...
        Barbour County            27226            27159  ...
        Bibb County               22733            22642  ...
        Blount County             57711            57776  ...

                        RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  \
STNAME  CTYNAME
Alabama Autauga County          7.242091         -2.915927         -3.012349
        Baldwin County         14.832960         17.647293         21.845705
        Barbour County         -4.728132         -2.500690         -7.056824
        Bibb County            -5.527043         -5.068871         -6.201001
        Blount County           1.807375         -1.177622         -1.748766

                        RDOMESTICMIG2014  RDOMESTICMIG2015  RNETMIG2011  \
STNAME  CTYNAME
Alabama Autauga County          2.265971         -2.530799     7.606016
        Baldwin County         19.243287         17.197872    15.844176
        Barbour County         -3.904217        -10.543299    -4.874741
        Bibb County            -0.177537          0.177258    -5.088389
        Blount County          -2.062535         -1.369970     1.859511

                        RNETMIG2012  RNETMIG2013  RNETMIG2014  RNETMIG2015
STNAME  CTYNAME
Alabama Autauga County    -2.626146    -2.722002     2.592270    -2.187333
        Baldwin County    18.559627    22.727626    20.317142    18.293499
        Barbour County    -2.758113    -7.167664    -3.978583   -10.543299
        Bibb County       -4.363636    -5.403729     0.754533     1.107861
        Blount County     -0.848580    -1.402476    -1.577232    -0.884411

[5 rows x 98 columns]

Perceba que para facilitar a leitura, ao invés de escrever tudo em uma linha, a qual ficaria gigante e de difícil percepção sobre o que está ocorrento, podemos colocar tudo dentro de parênteses, isto é:

- (df <br>
&emsp; .método1 <br>
&emsp; .método2 <br>
&emsp; ...)

Dessa forma, estamos dizendo ao Python que vamos estender essa instrução por várias linhas.

In [12]:
# Aqui está uma maneira mais tradicional e não pandorável de escrever isso:
# OBS: Não há nada de errado com o código em um sentido funcional, porém não é considerado tão pandorável quanto o primeiro exemplo. 

# Vamos ler novamente o CSV
df = pd.read_csv('datasets/census.csv')

# Realizar o uso dos métodos de forma NÃO pandorável
df = df[df['SUMLEV'] == 50] # Usando o operador de indexação sobrecarregado que descarta NaNs 

# Dessa forma, estamos fazendo algumas coisas. Estamos projetando e criando essa matriz booleana e estou usando isso para projetar apenas certos valores fora do DataFrame. Nenhum número de valores está sendo descartado automaticamente.

# Em seguida, atualizaremos o DataFrame para obtermos um novo índice e usaremos inplace = True para fazer isso no local. 
df.set_index(['STNAME', 'CTYNAME'], inplace = True)

# Agora, vamos definir o nome da coluna
df.rename(columns = {'ESTIMATESBASE2010': 'Estimates Base 2010'}, inplace = True)

# Vamos visualizar
df.head()

                        SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME  CTYNAME
Alabama Autauga County      50       3         6      1       1
        Baldwin County      50       3         6      1       3
        Barbour County      50       3         6      1       5
        Bibb County         50       3         6      1       7
        Blount County       50       3         6      1       9

                        CENSUS2010POP  Estimates Base 2010  POPESTIMATE2010  \
STNAME  CTYNAME
Alabama Autauga County          54571                54571            54660
        Baldwin County         182265               182265           183193
        Barbour County          27457                27457            27341
        Bibb County             22915                22919            22861
        Blount County           57322                57322            57373

                        POPESTIMATE2011  POPESTIMATE2012  ...  \
STNAME  CTYNAME                                           ...
Alabama Autauga County            55253            55175  ...
        Baldwin County           186659           190396  ...
        Barbour County            27226            27159  ...
        Bibb County               22733            22642  ...
        Blount County             57711            57776  ...

                        RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  \
STNAME  CTYNAME
Alabama Autauga County          7.242091         -2.915927         -3.012349
        Baldwin County         14.832960         17.647293         21.845705
        Barbour County         -4.728132         -2.500690         -7.056824
        Bibb County            -5.527043         -5.068871         -6.201001
        Blount County           1.807375         -1.177622         -1.748766

                        RDOMESTICMIG2014  RDOMESTICMIG2015  RNETMIG2011  \
STNAME  CTYNAME
Alabama Autauga County          2.265971         -2.530799     7.606016
        Baldwin County         19.243287         17.197872    15.844176
        Barbour County         -3.904217        -10.543299    -4.874741
        Bibb County            -0.177537          0.177258    -5.088389
        Blount County          -2.062535         -1.369970     1.859511

                        RNETMIG2012  RNETMIG2013  RNETMIG2014  RNETMIG2015
STNAME  CTYNAME
Alabama Autauga County    -2.626146    -2.722002     2.592270    -2.187333
        Baldwin County    18.559627    22.727626    20.317142    18.293499
        Barbour County    -2.758113    -7.167664    -3.978583   -10.543299
        Bibb County       -4.363636    -5.403729     0.754533     1.107861
        Blount County     -0.848580    -1.402476    -1.577232    -0.884411

[5 rows x 98 columns]

Perceba que obtivemos o mesmo resultado, mas precisamos entender quando a linguagem NÃO está nos ajudando. 

Nesse caso, podemos cronometrar os dois métodos para ver qual deles é executado mais rápido.

In [16]:
# Podemos colocar a abordagem em uma função e passar a função para o timeit para contar o tempo, o número do parâmetro por tempo 

def primeira_abordagem():
    global df

    return (df[df['SUMLEV'] == 50]
      .dropna()
      .set_index(['STNAME', 'CTYNAME'])
      .rename(columns = {'ESTIMATESBASE2010': 'Estimates Base 2010'}))

# Vamos ler novamente o conjunto de dados
df = pd.read_csv('datasets/census.csv')

# Agora vamos apenas executá-lo e cronometrar
timeit.timeit(primeira_abordagem, number = 100) # Vai fazer 100 vezes

0.9558435660000271

In [20]:
# Agora vamso testar a segunda abordagem 

def segunda_abordagem():
    global df

    novo_df = df[df['SUMLEV'] == 50]
    novo_df.set_index(['STNAME', 'CTYNAME'], inplace = True)
    return novo_df.rename(columns = {'ESTIMATESBASE2010': 'Estimates Base 2010'})

# Vamos ler novamente o conjunto de dados
df = pd.read_csv('datasets/census.csv')

# Vamos cronometrar novamente 
timeit.timeit(segunda_abordagem, number = 100)

0.7076940390000175

Perceba que houve um trade off entre tempo e legibilidade, uma vez que a segunda abordagem é ligeiramente mais rápida, porém é menos legível (pandorável)